# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    # Available environment: https://github.com/actions/virtual-environments
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # # Set up the running environment
    # - name: Build
    #   run: sudo apt-get install -y fftw3

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo $GITHUB_WORKSPACE
        pip3 install numpy
        python3 run.py
        if [[ $(cmp --silent res.dat ./test/ref.dat) = 1 ]]; then
          echo "files are the same"
        else
          echo "files are different:"
          cat res.dat
        fi
        echo $(cmp --silent res.dat ./test/ref.dat || "fail")
        echo here

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: exit 0

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: exit 1

    - name: The job has succeeded
      if: ${{ success() }}
      run: ehoc Success!