# Based on the basic GitHub workflow example

name: CI

# Triggers the workflow on push or pull request events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    # Available environments: https://github.com/actions/virtual-environments
    # It is possible and would be necessary to use Docker files
    # when cross-platform and parallel builds are required
    runs-on: ubuntu-latest

    steps:
    # Checks-out the repository under $GITHUB_WORKSPACE
    - name: Checkout main repo
      uses: actions/checkout@v2
      with:
        path: ci_test

    - name: Checkout support repo
      uses: actions/checkout@v2
      with:
        repository: smanist/ci_test_data
        path: ci_test_data

    - name: Test workspace
      run: |
        echo $GITHUB_WORKSPACE
        ls $GITHUB_WORKSPACE
        echo '1'
        ls /home/runner/work/ci_test
        echo '2'
        ls /home/runner/work/ci_test/ci_test
        echo '3'
        ls /home/runner/work/ci_test/ci_test_data

    # Part 1 - Not implemented
    # We need a way to check the coding style and documentation
    - name: Lint
      run: |
        exit 0

    # Part 2
    - name: Compile
      run: |
        pip3 install numpy
        # sudo apt-get install -y fftw3

    # Part 3 - Not implemented
    # Maybe driven by CTest
    - name: Unit tests
      run: |
        exit 0

    # Part 4
    - name: Regression test
      run: |
        echo $GITHUB_WORKSPACE
        python3 run.py
        cmp --silent res.dat ./test/ref.dat || exit 1
        echo DONE

    # Saves the results file
    - name: Finalize
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: res.dat
        path: res.dat

    # - name: The job has succeeded
    #   if: ${{ success() }}
    #   run: echo Success!

    # - name: The job has failed
    #   if: ${{ failure() }}
    #   run: echo Failed!
